version: '3.8'

services:

  gps-microservice:
    image: gps-microservice
    container_name: GpsMicroService
    build:
      context: GpsMicroService
      dockerfile: DockerFile.dockerfile
    ports:
      - "8081:8081"
    networks:
      - web-server-bridge
    restart: always

  rewards-microservice:
    image: rewards-microservice
    container_name: RewardMicroService
    build:
      context: RewardMicroService
      dockerfile: DockerFile.dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - gps-microservice
    networks:
      - web-server-bridge
    restart: always

  tripdeals-microservice:
    image: tripdeals-microservice
    container_name: TripDealMicroService
    build:
      context: TripDealsMicroService
      dockerfile: DockerFile.dockerfile
    ports:
      - "8083:8083"
    networks:
      - web-server-bridge
    restart: always

  tourguide:
    environment:
      - CLIENT_GPS_BASE_URL:http://localhost:8081/gps
      - CLIENT_REWARD_BASE_URL:http://localhost:8082/rewards
      - CLIENT_PROVIDER_BASE_URL:http://localhost:8083/tripDeals
    image: tourguide
    container_name: tourguide
    ports:
      - "8080:8080"
    build:
      context: TourGuide
      dockerfile: DockerFile.dockerfile
    depends_on:
      - gps-microservice
      - rewards-microservice
      - tripdeals-microservice
    networks:
      - web-server-bridge
    restart: always
    # restart: unless-stopped
    # standing_open: true

networks:
  web-server-bridge:
    driver: bridge